name: Mise à jour KlassDirect

on:
  schedule:
    # Tous les jeudis à 14h01
    - cron: '1 14 * * 4'
    # Tous les mardis et vendredis à 11h48
    - cron: '48 11 * * 2,5'
  workflow_dispatch:     # Permet de le lancer manuellement

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Robot
        env:
          ED_IDENTIFIANT: ${{ secrets.ED_IDENTIFIANT }}
          MOT_DE_PASSE: ${{ secrets.MOT_DE_PASSE }}
          ED_REPONSES: ${{ secrets.ED_REPONSES }}
        run: node mon_edt.js

      - name: 📥 Récupérer les captures et données
        if: always() # S'exécute même si le robot plante
        uses: actions/upload-artifact@v4
        with:
          # Nom unique pour éviter l'erreur 409 Conflict
          name: debug-${{ github.run_id }}-${{ github.run_attempt }}
          path: Site/
          retention-days: 1 # Garde les images 24h pour ne pas encombrer ton GitHub
