name: Mise à jour KlassDirect

on:
  schedule:
    - cron: '0 6 * * *' # Se lance tous les matins à 6h
  workflow_dispatch:     # Permet de le lancer manuellement

jobs:
  build:
    runs-on: ubuntu-latest # C'est ICI que tu l'ajoutes
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Version à jour

      - name: Install Node.js
        uses: actions/setup-node@v4 # Version à jour
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Robot
        env:
          ED_IDENTIFIANT: ${{ secrets.ED_IDENTIFIANT }}
          MOT_DE_PASSE: ${{ secrets.MOT_DE_PASSE }}
          ED_REPONSES: ${{ secrets.ED_REPONSES }}
        run: node mon_edt.js

       - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-screenshots-${{ github.run_id }}
          path: Site/
