name: Update Schedule Data

on:
  schedule:
    - cron: '0 * * * *' # S'exécute toutes les heures
  workflow_dispatch: # Permet de le lancer manuellement

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install puppeteer fs

      - name: Run Scraper
        run: node mon_edt.js
        env:
          ED_IDENTIFIANT: ${{ secrets.ED_IDENTIFIANT }}
          MOT_DE_PASSE: ${{ secrets.MOT_DE_PASSE }}
          ED_REPONSES: ${{ secrets.ED_REPONSES }}

      - name: Commit and Push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # On ajoute le fichier en précisant le chemin complet
          git add KlassDirect/Site/data_edt.json
          
          # Le commit ne se fera que s'il y a une modification réelle
          git commit -m "🚀 Mise à jour auto de l'emploi du temps" || exit 0
          git push
